name: Bug Report 🐛
description: Report a bug or issue
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: [@devinschumacher]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much information as you can about the issue you're experiencing. The more you provide, the easier & faster I can fix it.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please search the issues before submitting a new one
      options:
        - label: I have searched existing issues to make sure this hasn't been reported already
          required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: Please paste the exact error message you received
      placeholder: |
        Example: "Video failed to load: 404 Not Found"
        or "Playback error: unsupported format"
      render: shell
    validations:
      required: true

  - type: input
    id: video-page-url
    attributes:
      label: Webpage where video appears
      description: Please provide the URL where the video is embedded (ie the webpage your trying to download from)
      placeholder: ex. https://www.skool.com/community/classroom/d0825db2?md=eacef6223b5c41a4a49a2f5b59c4fc7d
    validations:
      required: true

  - type: input
    id: video-url
    attributes:
      label: Looom video URL (optional)
      description: Please the URL of the actual video (if you happen to have it)
      placeholder: ex. https://loom.com/video/123
    validations:
      required: false

  - type: input
    id: media-link
    attributes:
      label: Screencast (optional)
      description: Please provide a link to a screencast showing the issue (you can use a service like [zight](https://serp.ly/zight.com))
      placeholder: ex. https://www.zight.com/share/...
    validations:
      required: false

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Please provide any additional context about the issue
      placeholder: |
        - What were you trying to do when this happened?
        - Does this happen consistently or intermittently?
        - What browser/device are you using?
        - Any other relevant information
    validations:
      required: false

